- name: Remove apt packages
  apt: name={{item}} state=absent
  with_items:
    - chromium-browser

- name: Install apt packages
  apt: name={{item}}
  with_items:
    - htop
    - gdebi
    - vim
    - tree
    - firefox
    - remmina
    - ubuntu-wallpapers*
    - xclip
    - virtualbox-5.2

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install deb packages
  apt: deb={{item}}
  with_items:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - https://downloads.slack-edge.com/linux_releases/slack-desktop-3.1.1-amd64.deb

- name: Install snap packages
  command: snap install {{item}}
  with_items:
    - simplenote
    - pycharm-community --classic
