- name: Install apt packages
  apt: name={{item}}
  with_items:
    - htop
    - gdebi
    - vim
    - tree

- name: Install deb packages
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
