- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: InSync signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: ACCAF35C

- name: Add apt repositories
  apt_repository: repo={{item}}
  with_items:
    - ppa:remmina-ppa-team/remmina-next
    - deb https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib
