- name: Add apt repositories
  apt_repository: repo={{item}}
  with_items:
    - ppa:remmina-ppa-team/remmina-next
    - deb https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib

- name: Virtualbox Key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
