- name: Add apt keys
  apt_key: url={{item}}
  with_items:
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Add apt repositories
  apt_repository: repo={{item}}
  with_items:
    - ppa:remmina-ppa-team/remmina-next
    - deb https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib
